# Generated by Django 4.0.3 on 2022-04-11 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FireLoad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.CharField(max_length=4096, verbose_name='Материал')),
                ('heat', models.FloatField(null=True, verbose_name='Низшая теплота сгорания МДж/кг')),
            ],
        ),
        migrations.CreateModel(
            name='FireObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=4096, verbose_name='Название объекта')),
                ('length', models.FloatField(null=True, verbose_name='Длина')),
                ('width', models.FloatField(null=True, verbose_name='Ширина')),
                ('height', models.FloatField(null=True, verbose_name='Растояние от пожарной нагрузки до нижнего пояса ферм')),
                ('result', models.FloatField(blank=True, null=True, verbose_name='Площадь')),
                ('fire_load', models.ManyToManyField(blank=True, to='rkp.fireload')),
            ],
        ),
    ]
