# Generated by Django 4.0.3 on 2022-04-11 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rkp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quantity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField(null=True, verbose_name='Колличество кг')),
                ('fire_load', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='rkp.fireload')),
                ('fire_object', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='rkp.fireobject')),
            ],
        ),
    ]
