# Generated by Django 4.0.3 on 2022-04-11 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rkp', '0002_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quantity',
            name='fire_load',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='rkp.fireload'),
        ),
        migrations.AlterField(
            model_name='quantity',
            name='fire_object',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='rkp.fireobject'),
        ),
    ]
