# Generated by Django 4.0.3 on 2022-04-11 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rkp', '0003_alter_quantity_fire_load_alter_quantity_fire_object'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quantity',
            name='fire_object',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rkp.fireobject'),
        ),
    ]
