# Generated by Django 4.0.3 on 2022-04-15 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rkp', '0006_remove_fireobject_fire_load_quantity_material_q'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quantity',
            name='material_Q',
            field=models.FloatField(blank=True, null=True, verbose_name='Пожарная нагрузка МДж'),
        ),
    ]
