# Generated by Django 4.0.3 on 2022-04-15 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rkp', '0007_alter_quantity_material_q'),
    ]

    operations = [
        migrations.AddField(
            model_name='fireobject',
            name='production_category',
            field=models.CharField(blank=True, max_length=10, verbose_name='Категория производств'),
        ),
    ]
