# Generated by Django 4.0.3 on 2022-04-15 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rkp', '0009_fireobject_q_sum'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fireobject',
            old_name='Q_SUM',
            new_name='q_sum',
        ),
    ]
