# Generated by Django 4.0.4 on 2022-05-05 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rkp', '0010_rename_q_sum_fireobject_q_sum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fireobject',
            name='height',
            field=models.FloatField(null=True, verbose_name='Растояние от пожарной нагрузки до нижнего пояса ферм, м'),
        ),
        migrations.AlterField(
            model_name='fireobject',
            name='length',
            field=models.FloatField(null=True, verbose_name='Длина, м'),
        ),
        migrations.AlterField(
            model_name='fireobject',
            name='q_sum',
            field=models.FloatField(blank=True, null=True, verbose_name='Суммареая пожарная нагрузка МДж'),
        ),
        migrations.AlterField(
            model_name='fireobject',
            name='width',
            field=models.FloatField(null=True, verbose_name='Ширина, м'),
        ),
    ]
