# Generated by Django 4.0.4 on 2022-05-05 11:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rkp', '0011_alter_fireobject_height_alter_fireobject_length_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fireobject',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
