name: Django Deploy CD
on:
  push:
    branches: master
jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - name: Deploy to server
      # don't run locally
#         if: ${{ !env.ACT }}
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.LIVE_SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_USER_PASSWORD }}
          port: ${{ secrets.DEPLOY_PORT }}
          script: |
            cd ${{ secrets.PROJECT_PATH }}
            git pull ${{secrets.REPO_URL}}
            pipenv install --deploy
            pipenv run python manage.py migrate
            pipenv run python manage.py collectstatic --noinput
            systemctl restart rkp.target
